### ISSUE TITLE
Not receiving messages 

### ISSUE THREAD

**Issue by Salman98** [Rajat421/react-native-sms-retriever-api#1]
I am not receiving messages can you help me ??

**Comment by Rajat421** [comment]
@Salman98 This can happen because of three reason:-

1. 11 character string does not matches to your app, note hashstring for debug and release build will be differrent. trying generating your hash code using signature helper class

2. Check that your broadcast receiver  is resgistered properly or not, there are two ways to do that either you can register in android manifest file or in module itself.

3. check that  your broadcast receiver is listening to correct intent

**Comment by Salman98** [comment]
yes i missed this thing Thank you 👍 
1. 11 character string does not matches to your app, note hashstring for debug and release build will be differrent. trying generating your hash code using signature helper class
